export const GATEWAY_API = "http://10.0.0.2:30387/" //process.env.IS_ON_DEV === "true" ? "http://10.0.0.2:8095/" : "https://api.mtiyt.ru/"
export const AUTH_API = GATEWAY_API + "auth/"
export const PROBLEM_API = GATEWAY_API + "problems/"
export const FILES_SERVER = GATEWAY_API + "files/get/"
export const FILES_API = GATEWAY_API + "files/"
export const MATERIAL_API = GATEWAY_API + "materials/"
export const TOURNAMENTS_API = GATEWAY_API + "tournaments/"
export const REGISTRATION_API = GATEWAY_API + "registration/"
export const NOTIFICATIONS_API = GATEWAY_API + "notifications/"
export const USERS_API = GATEWAY_API + "users/"
